-- Préparé en local. Exécuter seulement lors de la publication groupée approuvée.
-- Sauvegarder projects auparavant. Seules les formulations encore présentes sont remplacées.
begin;
update public.projects set description = btrim(replace(description, 'L’ensemble a été réalisé afin de sécuriser la zone tout en conservant une intégration adaptée à l’environnement extérieur de la résidence.', '')) where slug = 'creation-d-un-mur-de-soutenement-en-betonflore' and strpos(description, 'L’ensemble a été réalisé afin de sécuriser la zone tout en conservant une intégration adaptée à l’environnement extérieur de la résidence.') > 0;
update public.projects set description = btrim(replace(description, 'L’intervention a permis de conserver l’usage de la cour tout en améliorant la gestion des eaux pluviales, avec une finition adaptée à un espace fréquenté quotidiennement.', '')) where slug = 'creation-regards-caniveaux-cour-recreation' and strpos(description, 'L’intervention a permis de conserver l’usage de la cour tout en améliorant la gestion des eaux pluviales, avec une finition adaptée à un espace fréquenté quotidiennement.') > 0;
update public.projects set description = btrim(replace(description, 'Une attention particulière a été portée à l’intégration des ouvrages dans l’environnement existant, avec des finitions soignées sur les zones carrossables, les cheminements piétons, les abords de la piscine et les accès extérieurs.', 'Les finitions concernent la voirie d’accès, les cheminements piétons et les abords de la piscine.')) where slug = 'voirie-reseaux-amenagement-exterieur-villa' and strpos(description, 'Une attention particulière a été portée à l’intégration des ouvrages dans l’environnement existant, avec des finitions soignées sur les zones carrossables, les cheminements piétons, les abords de la piscine et les accès extérieurs.') > 0;
update public.projects set initial_problem = btrim(replace(initial_problem, 'finitions extérieures qualitatives', 'finitions extérieures')) where slug = 'voirie-reseaux-amenagement-exterieur-villa' and strpos(initial_problem, 'finitions extérieures qualitatives') > 0;
update public.projects set description = btrim(replace(description, 'Les photos montrent les différentes étapes du chantier : zone balisée avant intervention, reprise du support, préparation de la structure, puis finition avec un enrobé noir propre et compacté.', 'Nous avons balisé la zone, repris le support et compacté le nouvel enrobé.')) where slug = 'refection-parking-enrobe-saint-raphael' and strpos(description, 'Les photos montrent les différentes étapes du chantier : zone balisée avant intervention, reprise du support, préparation de la structure, puis finition avec un enrobé noir propre et compacté.') > 0;
update public.projects set initial_problem = btrim(replace(initial_problem, 'L’objectif était de remettre la zone en état durablement.', '')) where slug = 'refection-parking-enrobe-saint-raphael' and strpos(initial_problem, 'L’objectif était de remettre la zone en état durablement.') > 0;
commit;
